# Generated by Django 5.2.1 on 2025-06-27 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_product_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name", "description", "price"],
                "permissions": [
                    ("can_unpublish_product", "Can unpublish product"),
                    ("delete_any_product", "Can delete any product"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
